version: "3"

services:
  lazarillo-embedded:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      labels:
        description:
    image: 
    networks:
      - embedded

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt_server
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - embedded

networks:
  - embedded
