version: "3"

services:
  lazarillo-embedded:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      labels:
        description:
    container_name: lazarillo-embedded
    networks:
      - embedded

  redis:
    image: redis:latest
    container_name: lazarillo-embedded_redis
    ports:
      - "6379:6379"
    networks:
      - embedded

networks:
  - embedded
